# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# If you are using Rails 5.2 or newer, consider using the
# encrypted credentials feature described here:
# http://edgeguides.rubyonrails.org/security.html#custom-credentials

development:
  domain_name: example.com
  secret_key_base: very_long_random_string
  telegram_token: '699449238:AAG65ShGj918_sWg60k_W9xeHK7orsr0ZE0'
  google_client_id:  752276571199-9dfahm6g9oert5765gf7m0nmi0t0ea85.apps.googleusercontent.com
  google_client_secret: Ca6Qt9YS2A9gv1oMO7KKYfE6


test:
  domain_name: example.com 
  secret_key_base: very_long_random_string

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram_token: '699449238:AAG65ShGj918_sWg60k_W9xeHK7orsr0ZE0'
  google_client_id:  752276571199-9dfahm6g9oert5765gf7m0nmi0t0ea85.apps.googleusercontent.com
  google_client_secret: Ca6Qt9YS2A9gv1oMO7KKYfE6
